# Generated by Django 3.2.25 on 2024-05-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='color',
        ),
    ]
