# Generated by Django 3.2.25 on 2024-05-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240512_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
