# Generated by Django 3.2.25 on 2024-05-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
