# Generated by Django 3.2.25 on 2024-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20240527_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_value',
            field=models.CharField(max_length=15),
        ),
    ]
