# Generated by Django 3.2.25 on 2024-05-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_orderlineitem_color'),
        ('products', '0014_alter_color_color_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
